name: Build Plugin

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          wget \
          python3 \
          python3-distutils \
          python3-setuptools \
          rsync \
          file \
          unzip \
          gawk \
          gettext \
          libncurses5-dev \
          zlib1g-dev \
          libssl-dev

    - name: Download SDK
      run: |
        wget https://downloads.openwrt.org/releases/21.02.0/targets/ramips/mt76x8/openwrt-sdk-21.02.0-ramips-mt76x8_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        tar -xf openwrt-sdk-*.tar.xz
    
    - name: Prepare Mosquitto
      run: |
        SDK_DIR=$(ls -d openwrt-sdk-* | head -n 1)
        cd $SDK_DIR
    
        ./scripts/feeds update -a
        ./scripts/feeds install mosquitto
    
        make defconfig
        make package/mosquitto/{clean,compile} V=s
        - name: Build
          run: |
            cd $(ls -d openwrt-sdk-* | head -n 1)
            STAGING_DIR=$(pwd)/staging_dir
    
            $STAGING_DIR/toolchain-mipsel_24kc_gcc-8.4.0_musl/bin/mipsel-openwrt-linux-musl-gcc \
              -fPIC -shared \
              -I$STAGING_DIR/target-mipsel_24kc_musl/usr/include \
              -o rewrite_topic.so \
              ../rewrite_topic_plugin.c

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: plugin
        path: openwrt-sdk-*/rewrite_topic.so
