name: Build Plugin

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install
      run: sudo apt update && sudo apt install -y wget build-essential

    - name: Download SDK
      run: |
        wget https://downloads.openwrt.org/releases/21.02.0/targets/ramips/mt76x8/openwrt-sdk-21.02.0-ramips-mt76x8_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        tar -xf openwrt-sdk-*.tar.xz

    - name: Build
      run: |
        cd openwrt-sdk-*
        STAGING_DIR=$(pwd)/staging_dir

        $STAGING_DIR/toolchain-mipsel_24kc_gcc-8.4.0_musl/bin/mipsel-openwrt-linux-musl-gcc \
          -fPIC -shared \
          -I$STAGING_DIR/target-mipsel_24kc_musl/usr/include \
          -o rewrite_topic.so \
          ../rewrite_topic_plugin.c

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: plugin
        path: openwrt-sdk-*/rewrite_topic.so
